# local variables
CC		= gcc
FLAGS 	= -Wall -Wextra -Werror

# rules
all:
	$(CC) $(FLAGS) ft_sort_string_tab.c -o ft_sort_string_tab

clean:
	rm -f ft_sort_string_tab

run:
	./ft_sort_string_tab

tests:
	./tests.sh